delete unused controller
This did not solve this error:
groovy.lang.MissingPropertyException: No such property: subject for
class: hightime.Question Possible solutions: subject